### ISSUE TITLE
After clone you get a cordova.js did not exist error

### ISSUE THREAD

**Issue by jakecraige** [poetic/ember-cli-cordova#104]
After cloning a project, you are unable to build because of this error:

```
ember-cli-cordova: /Users/user/app/cordova/platforms/ios/www/cordova.js did not exist. It is required for Device LiveReload to work.
```

You can't build cordova either because the `dist/` folder isn't created yet. The temp fix is to run this command:

```sh
mkdir dist && cd cordova && cordova build && cd ..
```

The solution for ember-cli-cordova would be to not throw this error if the dist directory doesn't exist yet.

**Comment by spruce** [comment]
I did have the same Problem. Gonna write a small PR for that

**Comment by BryanH** [comment]
Merged PR to fix this one

**Comment by spruce** [comment]
Thanks @matthewford :+1:
