### ISSUE TITLE
Android Platform :cannot connect to localhost:4200

### ISSUE THREAD

**Issue by kithokit** [poetic/ember-cli-cordova#105]
Hi after building the android platform on ember-cli-cordova
When I `ember server` up running the app, the android simulator shows error message 
cannot connect to localhost:4200

Have u ever meet this issue as well?

**Comment by adamesque** [comment]
FYI this doesn't appear to work currently, at least not with Android 5.1 — if I enable LiveReload, as soon as the app boots on the device, I get dumped out to Chrome, which tries to load the `emberUrl` URL in my config.

**Comment by AlexBlom** [comment]
I think this is a duplicate of #105. Please open again if that is not the case.
