### ISSUE TITLE
Support for Crosswalk builds on Android

### ISSUE THREAD

**Issue by vitch** [poetic/ember-cli-cordova#107]
[Crosswalk](https://crosswalk-project.org/) is a project that gives you access to an up to date chromium web view on Android. It's compatible with cordova and cordova plugins.

I currently have a pretty fragile system set up where I build a production ember app and use [steroids](http://www.appgyver.com/steroids) and the Appgyver build service to generate my crosswalk Android build with a specific Cordova plugin.

I'd love to be able to get rid of the other steps and do it all within `ember-cli` but it's pretty important for the performance and features of my app that I'm using Crosswalk rather than the native cordova web view.

I'm not involved what would be involved in getting `ember-cli-cordova` to play nicely with Crosswalk but I will try to investigate. I thought I'd open this issue first incase anyone else had any experience with this setup?

**Comment by xypaul** [comment]
What's the status on this? Would be cool to see Crosswalk as part of ember-cli-cordova :)

**Comment by runspired** [comment]
@xypaul partly waiting on a better config story, addons have started doing `config/addon-name.js` as a place to add this sort of configuration.  Partly just not enough man power.  You can use crosswalk with cordova and ember quite easily, but some of the command line niceties aren't going to work.

**Comment by xypaul** [comment]
Ah okay so I can add crosswalk with ember-cli-cordova and it will just work out of the box?

**Comment by joseph1125** [comment]
still waiting for this, I wish I can use crosswalk as it really helps to improve performance

**Comment by dukex** [comment]
To use crosswalk with cordova 4+ you need only install a plugin

```
$ cd cordova && cordova plugin add cordova-plugin-crosswalk-webview
```

https://crosswalk-project.org/documentation/cordova/cordova_4.html

**Comment by vitch** [comment]
I have finally got back to my project which needed this functionality and I can confirm that the `cordova-plugin-crosswalk-webview` works for me! Thanks @dukex :D
