### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by alexmngn** [poetic/ember-cli-cordova#125]
Hello,
I'm following the getting started guide on a new generated ember application, and I get an error when I run `ember server` after I installed `ember-cli-cordova` using `npm`:

`ember-cli-cordova: You must specify the locationType as 'hash' in your environment.js or rename it to defaultLocationType.`

Any idea what I should do?

Thanks.

**Comment by osxi** [comment]
Still an issue.

**Comment by dukex** [comment]
The Getting Started said:

> When you need to serve or build files for a browser environment (not for cordova) be sure to override the EMBER_CLI_CORDOVA environment variable to set it to a falsy value (0, no, off or false). It'll allow you to use locationType as specified in defaultLocationType and will not inject the cordova.js script tag.


Remove the locationTyoe and set defaultLocationType [see example](https://github.com/uhuraapp/uhura-dashboard/blob/master/config/environment.js#L4-L24):


``` js
 var ENV = {
    modulePrefix: 'uhuraapp',
    environment: environment,
    baseURL: '/',
    defaultLocationType: 'auto',
    EmberENV: {
      FEATURES: {
      //  'ember-htmlbars': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },

    cordova: {
      rebuildOnChange: false,
      emulate: false
    }
  };
```

**Comment by AlexBlom** [comment]
Closing this issue. Please re open if you are still facing challenges.
