### ISSUE TITLE
Uncaught TypeError: Cannot read property 'container' of undefined

### ISSUE THREAD

**Issue by ryanjones** [poetic/ember-cli-cordova#130]
Everything seemed to install just fine from the getting started guide, but when I run the local server with either EMBER_CLI_CORDOVA=0 ember serve (no cordova.js) - or just ember serve I end up with an error when I go to localhost:4200

Error @ hello.js:427
The line with the error: var View = this.container.lookupFactory("view:liquid-outlet");

package.json:

```
{
  "name": "example-app",
  "version": "0.0.0",
  "description": "Small description for example-app goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "broccoli-ember-hbs-template-compiler": "^1.6.1",
    "broccoli-sass": "^0.2.1",
    "ember-animated-outlet-mobile": "^2.0.0",
    "ember-cli": "0.2.0",
    "ember-cli-6to5": "^3.0.0",
    "ember-cli-app-version": "0.3.1",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-cordova": "0.0.15",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-fastclick": "1.0.3",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.1",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5"
  }
}
```

I'm not super familiar with the whole ecosystem, but I can provide anything from the project that might be helpful (let me know).

**Comment by MatthewHager** [comment]
It's an issue with liquid-fire: https://github.com/ef4/liquid-fire/issues/190. You'll need to upgrade to the master version. Currently it will try to use 0.18.x and the bug is present per the previous link.

**Comment by ryanjones** [comment]
Changing my package.json to point liquid-fire to the master version fixed the problem! Thanks!

package.json:
"liquid-fire": "git://github.com/ef4/liquid-fire.git"
