### ISSUE TITLE
Unable to find plugins at window.*

### ISSUE THREAD

**Issue by mattconstantine** [poetic/ember-cli-cordova#132]
I've created a new ember-cli app (0.2.2) and followed the instructions to add ember-cli-cordova. Then added two plugins both of which should be available on `window.*` but aren't.

`ember cordova plugin` returns:
```
Running 'cordova plugin'
com.synconset.imagepicker 1.0.6 "ImagePicker"
cordova-plugin-camera 0.3.7-dev "Camera"
```

My config options:
```
 cordova: {
      rebuildOnChange: false,
      emulate: false
    }
```
I'm not using liveReload, though I had it working and turned it off to debug this issue.

In my app I ran an `alert(!!window.camera)` and `alert(!!window.imagePicker)` both returning false. I haven't seen any obvious errors anywhere to indicate why these aren't available. Is there anything else I should check?

**Comment by mattconstantine** [comment]
Figured it out. I was checking on `document.onload` rather than using `deviceready`. Easy fix.

**Comment by MatthewHager** [comment]
Thanks for following up with the solution and closing this out!
