### ISSUE TITLE
Polymer's assets not included?

### ISSUE THREAD

**Issue by bugduino** [poetic/ember-cli-cordova#136]
Hi,
I created a new project with ember-cli-cordova v0.0.16 and added polymer following [this](http://www.programwitherik.com/how-to-add-polymer-to-your-ember-project/) simple tutorial.

In the browser it works like a charm, displaying the github card component, but when builded for android
the component is not displayed, it seems to not find assets.

I tryed to serve in the browser the ```cordova/www``` folder directly and the component works. 

Any ideas?
Thank you

**Comment by billybonks** [comment]
i cant check right now but maybe look at how this one is working 
https://github.com/blangslet/treasure-hunt

**Comment by AlexBlom** [comment]
Closing this as a stale issue. Please open again if you are having challenges.
