### ISSUE TITLE
ember serve - is trying to build ios app

### ISSUE THREAD

**Issue by jackmatt2** [poetic/ember-cli-cordova#138]
I created an android application via `ember g cordova-init my.domain --platform=android`

When I run `ember serve`, I get: 

```
Error thrown while running shell command: "cordova build ios"
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "cordova build ios"
```

Here is the output of the `cordova platforms ls`

```
Installed platforms: android 4.0.0
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, windows, windows8, wp8
```

As you can see there is no reference to ios at all.

**Comment by jackmatt2** [comment]
Solved it, in environment.js, liveReload.platform was set to ios.

    cordova: {
      rebuildOnChange: false,
      emulate: false,
      emberUrl: 'http://' + addresses[0] + ':4200',
      liveReload: {
        enabled: false,
        platform: 'ios'
      }
    }

**Comment by fpauser** [comment]
Same problem here, changing the env did not help.
