### ISSUE TITLE
`gap_init:2` popup

### ISSUE THREAD

**Issue by jackmatt2** [poetic/ember-cli-cordova#139]
When I go to l`http://ocalhost:4200` a popup with the text `gap_init:2` is displayed.  I can click the OK button and everything works find but it is kind of annoying because every time the app is changed the livereload shows the popup again.

**Comment by dukex** [comment]
This prompt is from [cordova-android](https://github.com/apache/cordova-android/search?utf8=%E2%9C%93&q=gap_init), run with:

```
EMBER_CLI_CORDOVA=false ember s
```

Using ```EMBER_CLI_CORDOVA=false``` the ember cli cordova will not put cordova.js on your index.html

**Comment by jackmatt2** [comment]
ok thanks

**Comment by AnbuIOS** [comment]
HI Team,

While Build the applcation in xcode "resources/cvcapture.bundle no such file or directory" error occured .
Please any body reply this issue
screenshot attached.
![ios error](https://cloud.githubusercontent.com/assets/20415344/16760848/5abd018a-483b-11e6-8143-e010a40f008e.png)


Thanks
Anbu

**Comment by BryanH** [comment]
@AnbuIOS Please do not add an unrelated question to another issue. Create a new issue and then we'll take a look.

Or you can ask on StackOverflow.
