### ISSUE TITLE
How to sign and publish to appstore

### ISSUE THREAD

**Issue by xypaul** [poetic/ember-cli-cordova#140]
Would be great to see a little guide in the docs how to sign apps for the app store & play store!

Also just from reading a few tutorials on how to do this - for example http://ionicframework.com/docs/guide/publishing.html, it also seems something that ember-cli-cordova could automate completely. Simply by providing the keys in a specified location, ember-cli-cordova could handle the rest.

Thoughts?

**Comment by dukex** [comment]
Hi @xypaul 
Today I use the [Makefile](https://github.com/uhuraapp/uhura-dashboard/blob/master/Makefile#L10-L15) to create the play store apk.

The google documentation is very userful see [Publishing](http://developer.android.com/tools/publishing/publishing_overview.html)

The only thing I missing in ember-cli-cordova is update android versionCode (I made a pull reques about it https://github.com/poetic/ember-cli-cordova/pull/127)

**Comment by xypaul** [comment]
@dukex very cool makefile. appreciate you sharing it :+1: 

Version code upgrade would be awesome :)

**Comment by dukex** [comment]
Thanks @xypaul
