### ISSUE TITLE
Windows 7: EPERM, symlink error

### ISSUE THREAD

**Issue by aaronpatty** [poetic/ember-cli-cordova#143]
Note that I'm using Windows 7 and attempting to build for android.

I'm super excited about using this, but I'm running into a bit of an issue. After following the directions to install everything (note that ember serve is dishing it up just fine in the browser!) I am not able to build the app for android:

When attempting: `ember cordova:build` or `ember cordova plugin add ...` I get the following response in the terminal:
```
version: 0.2.4
EPERM, symlink 'c:\<long path here\hello\cordova\www'
Error: EPERM, symlink 'c:\<long path here\hello\cordova\www'
    at Error (native)
```
I checked the `cordova` folder and discovered that there is no www folder or symlink folder present. After digging around in the issues I found #48 which indicated the symlinked www folder should point to  the dist folder in the root of the ember project. So, I created the symlink and was successfully able to run `ember cordova plugin ...` and `ember cordova platform ...` commands successfully! However, as soon as I ran `ember cordova:build` or `ember cordova:prepare` commands the symlinked `cordova\www` folder was immediately deleted and I would get the same error again!

How do I fix this?

Thanks again for your great work! I can't wait to use it!

Side note: I don't see anywhere in your documentation on how to properly reference cordova plugins within ember. I'm fairly new to both ember and cordova, so a quick tutorial on this would be much appreciated!

**Comment by dukex** [comment]
Hi @aaronpatty, I use ember-cli-cordova on windows and I got this same problem, I fixed running my terminal as administration(maybe I edit some policy). I belive normal users don't have permission to create hard links.

**Comment by dukex** [comment]
"In Windows 7 you need a special security privilege to create links and junctions. As administrator you can grant this permission to users using secpol.msc to set Local Policies\User Rights Assignment\Create symbolic links."

http://superuser.com/questions/193632/access-is-denied-error-when-i-mklink-on-windows-7

**Comment by aaronpatty** [comment]
Thanks dukex! I set the policy and still had to load the terminal as an admin, but it's working now!
