### ISSUE TITLE
Ember Data with custom Adapter Not Making Requests

### ISSUE THREAD

**Issue by Goldcap** [poetic/ember-cli-cordova#144]
I don't know if anyone else is having this issue, but using Ember CLI 0.2.3 with Ember Data Beta 16.1, I lost all use of my API via DS.RESTAdapter. Also, as a side note, I'm able to use Local Storage via DS.LSAdapter, but my DS.RESTAdapter just doesn't work. 

My current workaround was to use $.getJSON in a custom Object (which does work), so I'm not sure if this is on me, or if there is something else happening, but logging FWIW in case anyone else sees the same thing.  I'd do some further investigation, but the Web version works great, it's only on the device that I have issues, and I am fairly new to Cordova so not sure how to log device errors on my Android.

**Comment by AlexBlom** [comment]
Closing this as a stale issue. Please open again if you are having challenges.
