### ISSUE TITLE
EECCES unlink error

### ISSUE THREAD

**Issue by sunocean-sand** [poetic/ember-cli-cordova#154]
Everything was fine after just installing Ember-cli-cordova, but now it keeps sending me EACCES unlink errors every time I start ember. Is anyone else experiencing this?

I tried deleting the files it's asking me to, tried restarting Sublime (which was a problem for some people on a forum), and changing permissions but it keeps coming back. When I do "ember_cli_cordova=0 ember serve", it always adds back the files I deleted.

**Comment by sunocean-sand** [comment]
Update: it works when I do "sudo ember_cli_cordova=0 ember serve" ... it must be a permissions issue. Any idea on how to solve this permanently?

**Comment by AlexBlom** [comment]
Closing this as a stale issue. Did you happen to install any of your packages with sudo by mistake?

Please open again if you are having challenges.
