### ISSUE TITLE
Ember 1.13.0 Deprecations

### ISSUE THREAD

**Issue by devotox** [poetic/ember-cli-cordova#161]
cdv-generic-nav-bar just needs to use the new HTMLBars style like below

```
{{#if nav.leftButton.text}}
  <button {{action 'leftButton'}}>
	{{#if nav.leftButton.icon}}
	  <i class="icon {{nav.leftButton.icon}}"></i>
	{{/if}}
	{{nav.leftButton.text}}
  </button>
{{/if}}

{{#if nav.title.text}}
  <h1>
	{{nav.title.text}}
  </h1>
{{/if}}

{{#if nav.rightButton.text}}
  <button {{action 'rightButton'}}>
	{{#if nav.rightButton.icon}}
	  <i class="icon {{nav.rightButton.icon}}"></i>
	{{/if}}
	{{nav.rightButton.text}}
  </button>
{{/if}}
```

**Comment by kitsunde** [comment]
Both #150 and #148 is trying to fix this.

**Comment by timbaas** [comment]
+1

**Comment by vsymguysung** [comment]
+1

**Comment by Dragsbaek** [comment]
Any reasons this haven't been merged yet?

**Comment by shaunc** [comment]
Is this project still active? The underlying projects (ember, cordova) have been moving forward, but not much progress here. Is there a suggested alternative if this isn't active?

**Comment by runspired** [comment]
@shaunc I'm working on a replacement project that focuses on more than just cordova, join #mobile on the ember slack or #ember-cli-platforms

**Comment by shaunc** [comment]
@runspired -- Thanks for the info on #mobile ... (for the record: https://embercommunity.slack.com/archives/mobile/p1452369014001399)

**Comment by MatthewHager** [comment]
Anyone available/open to help maintain the repo? If so, let me know and I'll give you access.

**Comment by BryanH** [comment]
Merged.
