### ISSUE TITLE
Not all cordova events are forwarded correctly

### ISSUE THREAD

**Issue by xypaul** [poetic/ember-cli-cordova#162]
Not all cordova events are forwarded correctly. For example if I run:
```ember cordova -v```
> It simply returns the ember-cli version not the cordova version.

Simillar story if I want to run:
```cordova -d build android```
> I simply get the ember-cli version returned.

Is there a workaround for this?

**Comment by runspired** [comment]
yes, `cd cordova`, from there you can run any cordova command you regularly would

**Comment by xypaul** [comment]
@runspired thanks
