### ISSUE TITLE
Setting `platform: 'android'` in config/environment.js doesn't default me to android builds

### ISSUE THREAD

**Issue by adamesque** [poetic/ember-cli-cordova#164]
Not sure if this behavior is expected or not, but given that i have the following block in my config/environment.js:

```js
cordova: {
  rebuildOnChange: false,
  emulate: false,
  platform: 'android'
}
```

When I run `ember cordova:build`, it still tries to build an iOS app unless I explicitly pass the `--platform android` flag. Should setting the `platform` here change that default? If not, what does the `platform` setting affect?

**Comment by dukex** [comment]
@adamesque default always will be ios, see https://github.com/poetic/ember-cli-cordova/blob/master/lib/commands/build.js#L14

**Comment by dukex** [comment]
@adamesque I push a pull request about it #167
