### ISSUE TITLE
Ajax request failing in cordova/phonegap app on real device

### ISSUE THREAD

**Issue by Aathi** [poetic/ember-cli-cordova#181]
Hello,
I am facing an issue, I am making an ajax request from my app to get report summary. It works fine in the browser, but  It is not working in real device(Android and ios). I have noticed it is a PhoneGap issue. Is there any way to fix this issue in ember.

1. http://stackoverflow.com/questions/32743831/cordova-ajax-request-not-working
2. http://stackoverflow.com/questions/18263578/ajax-request-from-phonegap-android-fails
3. https://github.com/phonegap/phonegap-app-developer/issues/274

**Comment by BryanH** [comment]
Yes, you are running into a phonegap/cordova issue, which is the nature of running a hybrid app. 

Check out [ember-cli-content-security-policy](https://github.com/rwjblue/ember-cli-content-security-policy) for a possible solution.
