### ISSUE TITLE
Bump npm-version

### ISSUE THREAD

**Issue by Suven** [poetic/ember-cli-cordova#189]
Hi!

would be great if you could bump the version on npm. It's still at .17 there

**Comment by BryanH** [comment]
If you submit a pull request, we can merge it

**Comment by MatthewHager** [comment]
@BryanH he's talking about NPM. We need to package up a new version and submit that to NPM.

**Comment by Dragsbaek** [comment]
+1

**Comment by BryanH** [comment]
@MatthewHager Ahh - thanks, I misread it.

**Comment by vsymguysung** [comment]
Any update ?

**Comment by MatthewHager** [comment]
@BryanH I just added you as a collaborator on the NPM package. You should be able to push a new version.

**Comment by BryanH** [comment]
Done

**Comment by vsymguysung** [comment]
:+1:
