### ISSUE TITLE
How can I prevent the browser from opening when the app starts?

### ISSUE THREAD

**Issue by litao10422** [poetic/ember-cli-cordova#190]
I built an apk and installed it to my android phone by following the 'Getting started', the apk works, but it opens a browser while starting up, that is not what I expected.

How can I prevent the browser from opening when the app starts?

**Comment by simonihmig** [comment]
Probably the same issue as #174!?

**Comment by AlexBlom** [comment]
I think it is. Did that resolve for you?

**Comment by litao10422** [comment]
Hi, Thank you, simonihmig, AlexBlom.
I tried to add a line
  <allow-navigation href="http://10.0.2.2:4200/*" />
into /cordova
[Uploading config.xml.txt…]()
[Uploading config.xml.txt…]()

/config.xml, but a browser was still opened.
I made some mistakes?


![screenshot_2016-03-10-12-00-20](https://cloud.githubusercontent.com/assets/16515556/13659038/ed059b28-e6b7-11e5-9bae-609bac8c030b.png)

**Comment by litao10422** [comment]
hi, It works!
I changed the line as follows:

    <allow-navigation href="http://10.0.1.12:4200/*" />

since in \config\environment.js emberUrl is defined as:

    emberUrl: 'http://10.1.1.12:4200‘, 

Thank you very much!

**Comment by nicwillemse** [comment]
Im experiencing this on device - any tips ?
