### ISSUE TITLE
Does ember-cli-cordova support the POD structure?

### ISSUE THREAD

**Issue by litao10422** [poetic/ember-cli-cordova#198]
I use the POD structure in my ember.js application. It works well on the browser.

Then I transferred my code into the environment of ember-cli-cordova. Nothing shows on screen after I installed the app on my phone.

    [app]
        [application]
             template.hbs
        [index]
             route.js
             template.hbs

[application]template.hbs

    <h1>Template<h1>
    {{outlet}}

[index]template.hbs

    <h1>Index<h1>
    {{outlet}}

.ember-cli

    "usePods": true

What's wrong?
Thanks in advance!

**Comment by runspired** [comment]
Yes, ember-cli-cordova has no knowledge of nor cares whether pods is in use.  More likely something else is going wrong.

**Comment by litao10422** [comment]
Thank you very much, runspired. 
ember.js becomes to support the POD structure and I think it's convenient. 
Hope ember-cli-cordova can support it someday.

**Comment by runspired** [comment]
@litao10422 ember-cli-cordova does support it.... it supports it in the same way most things in Ember support it. ember-cli-cordova does not do anything that requires knowing about the structure of your asset organization.
