### ISSUE TITLE
Compatibility with PhoneGap

### ISSUE THREAD

**Issue by kibiz0r** [poetic/ember-cli-cordova#52]
Disclaimer: I'm fairly ignorant of the implications of the Cordova/PhoneGap separation, so this might be out of scope for this project.

I just started an Ember-based PhoneGap app. I'm excited to use ember-cli, but my team is more excited about the [PhoneGap live-reload thing](http://app.phonegap.com/).

Finding this project seemed like the perfect bridge between the two worlds, but it seems just one step short of what we ultimately need, which is to have all of the dist files end up in the www/ directory.

Is there a simple way to extend this project to conform to PhoneGap's expectations (AFAIK, just that built files end up under www/)?

Perhaps more importantly, is there a more fundamental mismatch between the existing Cordova target and my desired PhoneGap target?

My ideal use case is to use `ember serve` to live-reload in my browser while using `phonegap serve` to live-reload on my device.

**Comment by benedikt-d** [comment]
It does not seem to work with the new PhoneGap App Version Anymore.

Console spits out:
404 /__api__/appzip

And in the app it says: "Unable to download archive from the server. Please upgrade the Phonegap CLI or check your network settings."

Ember Cli Cordova: 0.0.17
Ember Cli: 0.2.5
Phonegap App Update on 19.05.2015
